### PR TITLE
Broadcast

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
@jwennerberg functionality looks good to me. Just type() needs to get be replaced for Puppet v4 compatibility. I can replace it.

**Comment by ghoneycutt** [comment]
@Phil-Friderici Thanks

**Comment by ghoneycutt** [comment]
@Phil-Friderici bump. changed type -> type3x as requested

**Comment by Phil-Friderici** [comment]
Thank you ! Released in v1.1.0

**Pull request closed without merging**
