### PR TITLE
Convert module to use PDK 2.1.1

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
@anders-larsson
Successfully locally tested to work with latest versions of Puppet 5, 6, and 7.

**Comment by anders-larsson** [comment]
Hello,

I forgot to tell that I do not have write access to repositories in the Ericsson organisation and my attempts to regain access have not gone well. Should we fork the project to kodguru and work from there instead?

Looks good otherwise. Maybe rebase and commit 4 "Use stdlib 5.2.0 " and 6 "Use stdlib 5.2.0 metadata.json" into one. You also might want to change the upper limit of the stdlib to < 8.0.0 instead. We've started testing stdlib version 7.x right now and it looks promising.

**Comment by anders-larsson** [comment]
Another thing we could update (maybe separate pull request(?) is to update supported OSes to include EL8, SLE15, and Ubuntu 20.04 (metadata + README). since we're already using this module for those operating systems

**Comment by Phil-Friderici** [comment]
@anders-larsson you have received an invitation for the Ericsson organisation. This should fix all your issues with that ;)

Let me work on the other topics you mentioned.

**Comment by Phil-Friderici** [comment]
Think I also should rebase both "Satisfy xxx" commits into one.

**Comment by Phil-Friderici** [comment]
Changed and rebased as needed. Added support for newer OSes.
Local PDK validation and tests were successfully for Puppet 5.5.22, 6.22.1, and 7.7.0.

Should be good to test & merge :)

**Comment by anders-larsson** [comment]
From what I can see there are no changes to the code so testing shouldn't be necessary or don't you agree?

Looks good to me!

**Comment by Phil-Friderici** [comment]
👍 yes you are right, the code isn't touched at all

**Pull request merged**
