### PR TITLE
Add comments to files maintained by puppet.

### PR DESCRIPTION
**Pull request by ejabach**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
:+1: @IvarBernes could you verify it ?

**Comment by IvarBernes** [comment]
The comment in /etc/defaultdomain breaks something... ypbind won't restart after it has been added. The comment in /etc/yp.conf can stay though, no issues there.

**Comment by Phil-Friderici** [comment]
@IvarBernes thanks for testing, btw nice icon you have :)
@ejabach could you please reverse the change on /etc/defaultdomain as the file is uncommentable ;)

**Comment by Phil-Friderici** [comment]
@ejabach nice opportunity to rebase ;)

**Comment by ejabach** [comment]
Should be done.

**Comment by Phil-Friderici** [comment]
@ejabach looks good :) Thanks !
@IvarBernes could you please give it another try ?

**Comment by Phil-Friderici** [comment]
@IvarBernes have you been able to test this yet ?

**Comment by IvarBernes** [comment]
Sry no, I havn't. Kinda forgot about it.   >.<
Will test it as soon there is an opportunity to do so.

**Comment by IvarBernes** [comment]
Tested on RHEL 6.5 and ubuntu 12.04 + 14.04 now. Looks good!

**Comment by Phil-Friderici** [comment]
@ejabach Thanks for coding
@IvarBernes Thanks for testing
@jwennerberg do you mind merging this ?

**Comment by jwennerberg** [comment]
Merged in #26 (changed the commit message)

**Comment by Phil-Friderici** [comment]
Thanks gents !

**Pull request closed without merging**
